# coding: utf-8

Question.create(content: " 選択した項目を切り取ります。" )
Question.create(content: " 選択した項目をクリップボードにコピーします。" )
Question.create(content: "クリップボードの内容を現在の書類または App にペーストします。" )
Question.create(content: "項目をすべて選択します。" )
Question.create(content: "直前のコマンドを取り消します。" )
Question.create(content: "書類内の項目を検索します。" )
Question.create(content: "直前に検索した項目が次に出現する箇所を探します。" )
Question.create(content: "最前面の App のウインドウを非表示にします。" )
Question.create(content: "最前面のウインドウを最小化して Dock にしまいます。" )
Question.create(content: "選択した項目を開きます。" )
Question.create(content: "現在の書類をプリントします。" )
Question.create(content: "現在の書類を保存します。" )
Question.create(content: "新しいタブを開きます。" )
Question.create(content: "最前面のウインドウを閉じます。" )
Question.create(content: "App を強制終了します。" )
Question.create(content: "検索フィールドの表示／非表示を切り替えます。" )
Question.create(content: "文字ビューアを表示します。" )
Question.create(content: "App をフルスクリーンで使います。" )
Question.create(content: "開いている App のうち、最近使った順番で次にあたる App に切り替えます。 " )
Question.create(content: "スクリーンショットを撮ります。" )
Question.create(content: "Finder で新しいフォルダを作成します。" )
Question.create(content: "選択したファイルを複製します。" )
Question.create(content: "選択したディスクまたはボリュームを取り出します。" )
Question.create(content: "Finder ウインドウで Spotlight 検索を開始します。" )
Question.create(content: "選択したファイルの「情報を見る」ウインドウを表示します。" )
Question.create(content: "ページを更新または再読み込みします。" )
Question.create(content: "「コンピュータ」ウインドウを開きます。" )
Question.create(content: "「デスクトップ」フォルダを開きます。" )
Question.create(content: "「最近使った項目」ウインドウを開きます。" )
Question.create(content: "「フォルダへ移動」ウインドウを開きます。" )
Question.create(content: "現在の macOS ユーザアカウントのホームフォルダを開きます。" )
Question.create(content: "iCloud Drive を開きます。" )
Question.create(content: "「ネットワーク」ウインドウを開きます。" )
Question.create(content: "「ダウンロード」フォルダを開きます。" )
Question.create(content: "新しいフォルダを作成します。" )
Question.create(content: "「書類」フォルダを開きます。" )
Question.create(content: "Finder ウインドウのプレビューパネルの表示／非表示を切り替えます。" )
Question.create(content: "Finder ウインドウのタブバーの表示／非表示を切り替えます。 " )
Question.create(content: "Finder で選択した項目を Dock に追加します。" )
Question.create(content: "「ユーティリティ」フォルダを開きます。" )
Question.create(content: "Dock の表示／非表示を切り替えます。 " )
Question.create(content: "選択した項目をサイドバーに追加します。" )
Question.create(content: "Finder ウインドウのパスバーの表示／非表示を切り替えます。" )
Question.create(content: "Finder ウインドウのサイドバーの非表示／表示を切り替えます。" )
Question.create(content: "Finder ウインドウのステータスバーの非表示／表示を切り替えます。" )
Question.create(content: "表示オプションを表示します。" )
Question.create(content: "「サーバへ接続」ウインドウを開きます。" )
Question.create(content: "「AirDrop」ウインドウを開きます。" )
Question.create(content: "選択した項目のエイリアスを作成します。" )
Question.create(content: "Finder の新しいウインドウを開きます。" )

Choice.create(text: "command + X" )
Choice.create(text: "command + C" )
Choice.create(text: "command + V" )
Choice.create(text: "command + A" )
Choice.create(text: "command + Z" )
Choice.create(text: "command + F" )
Choice.create(text: "command + G" )
Choice.create(text: "command + H" )
Choice.create(text: "command + M" )
Choice.create(text: "command + O" )
Choice.create(text: "command + P" )
Choice.create(text: "command + S" )
Choice.create(text: "command + T" )
Choice.create(text: "command + W" )
Choice.create(text: "option + command + esc" )
Choice.create(text: "command + スペース" )
Choice.create(text: "control + command + スペース" )
Choice.create(text: "control + command + F" )
Choice.create(text: "command + tab" )
Choice.create(text: "shift + command + 3" )
Choice.create(text: "shift + command + N" )
Choice.create(text: "command + D" )
Choice.create(text: "command + E" )
Choice.create(text: "command + F" )
Choice.create(text: "command + I" )
Choice.create(text: "command + R" )
Choice.create(text: "shift + command + C" )
Choice.create(text: "shift + command + D" )
Choice.create(text: "shift + command + F" )
Choice.create(text: "shift + command + G" )
Choice.create(text: "shift + command + H" )
Choice.create(text: "shift + command + I" )
Choice.create(text: "shift + command + K" )
Choice.create(text: "option + command + L" )
Choice.create(text: "shift + command + N" )
Choice.create(text: "shift + command + O" )
Choice.create(text: "shift + command + P" )
Choice.create(text: "shift + command + T" )
Choice.create(text: "control + shift + command + T" )
Choice.create(text: "shift + command + U" )
Choice.create(text: "option + command + D" )
Choice.create(text: "control + command + T" )
Choice.create(text: "option + command + P" )
Choice.create(text: "option + command + S" )
Choice.create(text: "command + スラッシュ (/)" )
Choice.create(text: "command + J" )
Choice.create(text: "command + K" )
Choice.create(text: "shift + command + R" )
Choice.create(text: "control + command + A" )
Choice.create(text: "command + N" )