# coding: utf-8

Question.create(content: " 選択した項目を切り取ります。" )
Question.create(content: " 選択した項目をクリップボードにコピーします。" )
Question.create(content: "クリップボードの内容を現在の書類または App にペーストします。" )
Question.create(content: "項目をすべて選択します。" )
Question.create(content: "直前のコマンドを取り消します。" )
Question.create(content: "書類内の項目を検索します。" )
Question.create(content: "直前に検索した項目が次に出現する箇所を探します。" )
Question.create(content: "最前面の App のウインドウを非表示にします。" )
Question.create(content: "最前面のウインドウを最小化して Dock にしまいます。" )
Question.create(content: "選択した項目を開きます。" )
Question.create(content: "現在の書類をプリントします。" )
Question.create(content: "現在の書類を保存します。" )
Question.create(content: "新しいタブを開きます。" )
Question.create(content: "最前面のウインドウを閉じます。" )
Question.create(content: "App を強制終了します。" )
Question.create(content: "検索フィールドの表示／非表示を切り替えます。" )
Question.create(content: "文字ビューアを表示します。" )
Question.create(content: "App をフルスクリーンで使います。" )
Question.create(content: "開いている App のうち、最近使った順番で次にあたる App に切り替えます。 " )
Question.create(content: "スクリーンショットを撮ります。" )
Question.create(content: "Finder で新しいフォルダを作成します。" )
Question.create(content: "選択したファイルを複製します。" )
Question.create(content: "選択したディスクまたはボリュームを取り出します。" )
Question.create(content: "Finder ウインドウで Spotlight 検索を開始します。" )
Question.create(content: "選択したファイルの「情報を見る」ウインドウを表示します。" )
Question.create(content: "ページを更新または再読み込みします。" )
Question.create(content: "「コンピュータ」ウインドウを開きます。" )
Question.create(content: "「デスクトップ」フォルダを開きます。" )
Question.create(content: "「最近使った項目」ウインドウを開きます。" )
Question.create(content: "「フォルダへ移動」ウインドウを開きます。" )
Question.create(content: "現在の macOS ユーザアカウントのホームフォルダを開きます。" )
Question.create(content: "iCloud Drive を開きます。" )
Question.create(content: "「ネットワーク」ウインドウを開きます。" )
Question.create(content: "「ダウンロード」フォルダを開きます。" )
Question.create(content: "新しいフォルダを作成します。" )
Question.create(content: "「書類」フォルダを開きます。" )
Question.create(content: "Finder ウインドウのプレビューパネルの表示／非表示を切り替えます。" )
Question.create(content: "Finder ウインドウのタブバーの表示／非表示を切り替えます。 " )
Question.create(content: "Finder で選択した項目を Dock に追加します。" )
Question.create(content: "「ユーティリティ」フォルダを開きます。" )
Question.create(content: "Dock の表示／非表示を切り替えます。 " )
Question.create(content: "選択した項目をサイドバーに追加します。" )
Question.create(content: "Finder ウインドウのパスバーの表示／非表示を切り替えます。" )
Question.create(content: "Finder ウインドウのサイドバーの非表示／表示を切り替えます。" )
Question.create(content: "Finder ウインドウのステータスバーの非表示／表示を切り替えます。" )
Question.create(content: "表示オプションを表示します。" )
Question.create(content: "「サーバへ接続」ウインドウを開きます。" )
Question.create(content: "「AirDrop」ウインドウを開きます。" )
Question.create(content: "選択した項目のエイリアスを作成します。" )
Question.create(content: "Finder の新しいウインドウを開きます。" )
Question.create(content: "選択したテキストを太字にします。" )
Question.create(content: "選択したテキストを斜体にします。" )
Question.create(content: "Web リンクを追加します。" )
Question.create(content: "選択したテキストに下線を引きます。" )
Question.create(content: "「フォント」ウインドウの表示／非表示を切り替えます。" )
Question.create(content: "「開く」ダイアログまたは「保存」ダイアログ内で、「デスクトップ」フォルダを選択します。" )
Question.create(content: "選択した単語の定義の表示／非表示を切り替えます。" )
Question.create(content: "「スペルと文法」ウインドウを表示します。" )
Question.create(content: "書類内でスペルに誤りのある単語を検索します。" )
Question.create(content: "挿入ポイントの左側にある単語を削除します。" )
Question.create(content: "挿入ポイントの左側にある文字を削除します。" )
Question.create(content: "挿入ポイントの右側にある文字を削除します。" )
Question.create(content: "挿入ポイントから、行または段落の末尾までの範囲にあるテキストを削除します。" )
Question.create(content: "page up：1 ページ分上にスクロールします。 " )
Question.create(content: "page down：1 ページ分下にスクロールします。" )
Question.create(content: "home：書類の先頭までスクロールします。" )
Question.create(content: "end：書類の末尾までスクロールします。" )
Question.create(content: "挿入ポイントを書類の先頭に移動します。" )
Question.create(content: "挿入ポイントを書類の末尾に移動します。" )
Question.create(content: "挿入ポイントを現在の行の先頭に移動します。" )
Question.create(content: "挿入ポイントを現在の行の末尾に移動します。" )
Question.create(content: "挿入ポイントを前の単語の先頭に移動します。" )
Question.create(content: "挿入ポイントを次の単語の末尾に移動します。" )
Question.create(content: "挿入ポイントから、書類の先頭までの範囲のテキストを選択します。" )
Question.create(content: "挿入ポイントから、書類の末尾までの範囲のテキストを選択します。" )
Question.create(content: "挿入ポイントから、現在の行の先頭までの範囲のテキストを選択します。" )
Question.create(content: "挿入ポイントから、現在の行の末尾までの範囲のテキストを選択します。" )
Question.create(content: "選択したテキスト範囲を、1 つ上の行の、水平位置が最も近い文字まで拡張します。" )
Question.create(content: "選択したテキスト範囲を、1 つ下の行の、水平位置が最も近い文字まで拡張します。" )
Question.create(content: "選択したテキスト範囲を 1 文字分左に拡張します。" )
Question.create(content: "選択したテキスト範囲を 1 文字分右に拡張します。" )
Question.create(content: "選択したテキスト範囲を、現在の段落の先頭まで拡張します。" )
Question.create(content: "選択したテキスト範囲を、現在の段落の末尾まで拡張します。" )
Question.create(content: "選択したテキスト範囲を、現在の単語の先頭まで拡張します。" )
Question.create(content: "選択したテキスト範囲を、現在の単語の末尾まで拡張します。" )
Question.create(content: "行または段落の先頭に移動します。" )
Question.create(content: "行または段落の末尾に移動します。" )
Question.create(content: "1 文字分進みます。" )
Question.create(content: "1 文字分戻ります。" )
Question.create(content: "カーソルまたは選択範囲を表示領域の中央に表示します。" )
Question.create(content: "1 行上に移動します。" )
Question.create(content: "1 行下に移動します。" )
Question.create(content: "挿入ポイントの後に 1 行挿入します。" )
Question.create(content: "挿入ポイントの右側の文字と左側の文字を置換します。" )
Question.create(content: "左揃えにします。" )
Question.create(content: "右揃えにします。" )
Question.create(content: "中央揃えにします。" )
Question.create(content: "検索フィールドに移動します。" )
Question.create(content: "App のツールバーの表示／非表示を切り替えます。" )
Question.create(content: "スタイルをコピー：選択した項目の書式設定をクリップボードにコピーします。" )
Question.create(content: "スタイルをペースト：コピーしたスタイルを、選択した項目に適用します。" )
Question.create(content: "周りのコンテンツと同じスタイルを適用してペーストします" )
Question.create(content: "「インスペクタ」ウインドウの表示／非表示を切り替えます。" )
Question.create(content: "ページ設定：書類設定を選択するためのウインドウを表示します。" )
Question.create(content: "「別名で保存」ダイアログを表示します。または、現在の書類を複製します。" )
Question.create(content: "選択した項目のサイズを縮小します。" )
Question.create(content: "選択した項目のサイズを拡大します。" )
Question.create(content: "「ヘルプ」メニューを開きます。" )

Choice.create(text: "command + X" )
Choice.create(text: "command + C" )
Choice.create(text: "command + V" )
Choice.create(text: "command + A" )
Choice.create(text: "command + Z" )
Choice.create(text: "command + F" )
Choice.create(text: "command + G" )
Choice.create(text: "command + H" )
Choice.create(text: "command + M" )
Choice.create(text: "command + O" )
Choice.create(text: "command + P" )
Choice.create(text: "command + S" )
Choice.create(text: "command + T" )
Choice.create(text: "command + W" )
Choice.create(text: "option + command + esc" )
Choice.create(text: "command + スペース" )
Choice.create(text: "control + command + スペース" )
Choice.create(text: "control + command + F" )
Choice.create(text: "command + tab" )
Choice.create(text: "shift + command + 3" )
Choice.create(text: "shift + command + N" )
Choice.create(text: "command + D" )
Choice.create(text: "command + E" )
Choice.create(text: "command + F" )
Choice.create(text: "command + I" )
Choice.create(text: "command + R" )
Choice.create(text: "shift + command + C" )
Choice.create(text: "shift + command + D" )
Choice.create(text: "shift + command + F" )
Choice.create(text: "shift + command + G" )
Choice.create(text: "shift + command + H" )
Choice.create(text: "shift + command + I" )
Choice.create(text: "shift + command + K" )
Choice.create(text: "option + command + L" )
Choice.create(text: "shift + command + O" )
Choice.create(text: "shift + command + P" )
Choice.create(text: "shift + command + T" )
Choice.create(text: "control + shift + command + T" )
Choice.create(text: "shift + command + U" )
Choice.create(text: "option + command + D" )
Choice.create(text: "control + command + T" )
Choice.create(text: "option + command + P" )
Choice.create(text: "option + command + S" )
Choice.create(text: "command + スラッシュ (/)" )
Choice.create(text: "command + J" )
Choice.create(text: "command + K" )
Choice.create(text: "shift + command + R" )
Choice.create(text: "control + command + A" )
Choice.create(text: "command + N" )
Choice.create(text: "command + B" )
Choice.create(text: "command + I" )
Choice.create(text: "command + K" )
Choice.create(text: "command + U" )
Choice.create(text: "command + T" )
Choice.create(text: "command + D" )
Choice.create(text: "control + command + D" )
Choice.create(text: "shift + command + コロン (:)" )
Choice.create(text: "command + セミコロン (;)" )
Choice.create(text: "option + delete" )
Choice.create(text: "control + H" )
Choice.create(text: "control + D" )
Choice.create(text: "control + K" )
Choice.create(text: "fn + 上矢印" )
Choice.create(text: "fn + 下矢印" )
Choice.create(text: "fn + 左矢印" )
Choice.create(text: "fn + 右矢印" )
Choice.create(text: "command + 上矢印" )
Choice.create(text: "command + 下矢印" )
Choice.create(text: "command + 左矢印" )
Choice.create(text: "command + 右矢印" )
Choice.create(text: "option + 左矢印" )
Choice.create(text: "option + 右矢印" )
Choice.create(text: "shift + command + 上矢印" )
Choice.create(text: "shift + command + 下矢印" )
Choice.create(text: "shift + command + 左矢印" )
Choice.create(text: "shift + command + 右矢印" )
Choice.create(text: "shift + 上矢印" )
Choice.create(text: "shift + 下矢印" )
Choice.create(text: "shift + 左矢印" )
Choice.create(text: "shift + 右矢印" )
Choice.create(text: "option + shift + 上矢印" )
Choice.create(text: "option + shift + 下矢印" )
Choice.create(text: "option + shift + 左矢印" )
Choice.create(text: "option + shift + 右矢印" )
Choice.create(text: "control + A" )
Choice.create(text: "control + E" )
Choice.create(text: "control + F" )
Choice.create(text: "control + B" )
Choice.create(text: "control + L" )
Choice.create(text: "control + P" )
Choice.create(text: "control + N" )
Choice.create(text: "control + O" )
Choice.create(text: "control + T" )
Choice.create(text: "command + { (左中かっこ)" )
Choice.create(text: "command + } (右中かっこ)" )
Choice.create(text: "shift + command + 縦棒 (|)" )
Choice.create(text: "option + command + F" )
Choice.create(text: "option + command + T" )
Choice.create(text: "option + command + C" )
Choice.create(text: "option + command + V" )
Choice.create(text: "option + shift + command + V" )
Choice.create(text: "option + command + I" )
Choice.create(text: "shift + command + P" )
Choice.create(text: "shift + command + S" )
Choice.create(text: "shift + command + マイナス(-)" )
Choice.create(text: "shift + command + プラス(+)" )
Choice.create(text: "shift + command + 疑問符 (?)" )